-- Script SQL para crear e insertar datos de paises del mundo
-- Generado automaticamente

INSERT INTO paises (pais, nacionalidad, iso2, iso3) VALUES
('Argelia', 'argelino', 'DZ', 'DZA'),
('Angola', 'angoleño', 'AO', 'AGO'),
('Benín', 'beninés', 'BJ', 'BEN'),
('Botsuana', 'botsuano', 'BW', 'BWA'),
('Burkina Faso', 'burkinés', 'BF', 'BFA'),
('Burundi', 'burundés', 'BI', 'BDI'),
('Cabo Verde', 'caboverdiano', 'CV', 'CPV'),
('Camerún', 'camerunés', 'CM', 'CMR'),
('Chad', 'chadiano', 'TD', 'TCD'),
('Comoras', 'comorense', 'KM', 'COM'),
('Congo', 'congoleño', 'CG', 'COG'),
('República Democrática del Congo', 'congoleño', 'CD', 'COD'),
('Costa de Marfil', 'marfileño', 'CI', 'CIV'),
('Yibuti', 'yibutiano', 'DJ', 'DJI'),
('Egipto', 'egipcio', 'EG', 'EGY'),
('Eritrea', 'eritreo', 'ER', 'ERI'),
('Esuatini', 'esuatino', 'SZ', 'SWZ'),
('Etiopía', 'etíope', 'ET', 'ETH'),
('Gabón', 'gabonés', 'GA', 'GAB'),
('Gambia', 'gambiano', 'GM', 'GMB'),
('Ghana', 'ghanés', 'GH', 'GHA'),
('Guinea', 'guineano', 'GN', 'GIN'),
('Guinea-Bisáu', 'guineano', 'GW', 'GNB'),
('Guinea Ecuatorial', 'ecuatoguineano', 'GQ', 'GNQ'),
('Kenia', 'keniano', 'KE', 'KEN'),
('Lesoto', 'lesotense', 'LS', 'LSO'),
('Liberia', 'liberiano', 'LR', 'LBR'),
('Libia', 'libio', 'LY', 'LBY'),
('Madagascar', 'malgache', 'MG', 'MDG'),
('Malaui', 'malauí', 'MW', 'MWI'),
('Malí', 'maliense', 'ML', 'MLI'),
('Marruecos', 'marroquí', 'MA', 'MAR'),
('Mauricio', 'mauriciano', 'MU', 'MUS'),
('Mauritania', 'mauritano', 'MR', 'MRT'),
('Mozambique', 'mozambiqueño', 'MZ', 'MOZ'),
('Namibia', 'namibio', 'NA', 'NAM'),
('Níger', 'nigerino', 'NE', 'NER'),
('Nigeria', 'nigeriano', 'NG', 'NGA'),
('República Centroafricana', 'centroafricano', 'CF', 'CAF'),
('Ruanda', 'ruandés', 'RW', 'RWA'),
('Santo Tomé y Príncipe', 'santotomense', 'ST', 'STP'),
('Senegal', 'senegalés', 'SN', 'SEN'),
('Seychelles', 'seychellense', 'SC', 'SYC'),
('Sierra Leona', 'sierraleonés', 'SL', 'SLE'),
('Somalia', 'somalí', 'SO', 'SOM'),
('Sudáfrica', 'sudafricano', 'ZA', 'ZAF'),
('Sudán', 'sudanés', 'SD', 'SDN'),
('Sudán del Sur', 'sursudanés', 'SS', 'SSD'),
('Tanzania', 'tanzano', 'TZ', 'TZA'),
('Togo', 'togolés', 'TG', 'TGO'),
('Túnez', 'tunecino', 'TN', 'TUN'),
('Uganda', 'ugandés', 'UG', 'UGA'),
('Zambia', 'zambiano', 'ZM', 'ZMB'),
('Zimbabue', 'zimbabuense', 'ZW', 'ZWE'),
('Antigua y Barbuda', 'antiguano', 'AG', 'ATG'),
('Argentina', 'argentino', 'AR', 'ARG'),
('Bahamas', 'bahamés', 'BS', 'BHS'),
('Barbados', 'barbadense', 'BB', 'BRB'),
('Belice', 'beliceño', 'BZ', 'BLZ'),
('Bolivia', 'boliviano', 'BO', 'BOL'),
('Brasil', 'brasileño', 'BR', 'BRA'),
('Canadá', 'canadiense', 'CA', 'CAN'),
('Chile', 'chileno', 'CL', 'CHL'),
('Colombia', 'colombiano', 'CO', 'COL'),
('Costa Rica', 'costarricense', 'CR', 'CRI'),
('Cuba', 'cubano', 'CU', 'CUB'),
('Dominica', 'dominiqués', 'DM', 'DMA'),
('Ecuador', 'ecuatoriano', 'EC', 'ECU'),
('El Salvador', 'salvadoreño', 'SV', 'SLV'),
('Estados Unidos', 'estadounidense', 'US', 'USA'),
('Granada', 'granadino', 'GD', 'GRD'),
('Guatemala', 'guatemalteco', 'GT', 'GTM'),
('Guyana', 'guyanés', 'GY', 'GUY'),
('Haití', 'haitiano', 'HT', 'HTI'),
('Honduras', 'hondureño', 'HN', 'HND'),
('Jamaica', 'jamaicano', 'JM', 'JAM'),
('México', 'mexicano', 'MX', 'MEX'),
('Nicaragua', 'nicaragüense', 'NI', 'NIC'),
('Panamá', 'panameño', 'PA', 'PAN'),
('Paraguay', 'paraguayo', 'PY', 'PRY'),
('Perú', 'peruano', 'PE', 'PER'),
('República Dominicana', 'dominicano', 'DO', 'DOM'),
('San Cristóbal y Nieves', 'sankitiano', 'KN', 'KNA'),
('San Vicente y las Granadinas', 'sanvicentino', 'VC', 'VCT'),
('Santa Lucía', 'santalucense', 'LC', 'LCA'),
('Surinam', 'surinamés', 'SR', 'SUR'),
('Trinidad y Tobago', 'trinitense', 'TT', 'TTO'),
('Uruguay', 'uruguayo', 'UY', 'URY'),
('Venezuela', 'venezolano', 'VE', 'VEN'),
('Afganistán', 'afgano', 'AF', 'AFG'),
('Arabia Saudita', 'saudí', 'SA', 'SAU'),
('Armenia', 'armenio', 'AM', 'ARM'),
('Azerbaiyán', 'azerbaiyano', 'AZ', 'AZE'),
('Baréin', 'bareiní', 'BH', 'BHR'),
('Bangladés', 'bangladesí', 'BD', 'BGD'),
('Bután', 'butanés', 'BT', 'BTN'),
('Brunéi', 'bruneano', 'BN', 'BRN'),
('Camboya', 'camboyano', 'KH', 'KHM'),
('Catar', 'catarí', 'QA', 'QAT'),
('China', 'chino', 'CN', 'CHN'),
('Chipre', 'chipriota', 'CY', 'CYP'),
('Corea del Norte', 'norcoreano', 'KP', 'PRK'),
('Corea del Sur', 'surcoreano', 'KR', 'KOR'),
('Emiratos Árabes Unidos', 'emiratí', 'AE', 'ARE'),
('Filipinas', 'filipino', 'PH', 'PHL'),
('Georgia', 'georgiano', 'GE', 'GEO'),
('India', 'indio', 'IN', 'IND'),
('Indonesia', 'indonesio', 'ID', 'IDN'),
('Irak', 'iraquí', 'IQ', 'IRQ'),
('Irán', 'iraní', 'IR', 'IRN'),
('Israel', 'israelí', 'IL', 'ISR'),
('Japón', 'japonés', 'JP', 'JPN'),
('Jordania', 'jordano', 'JO', 'JOR'),
('Kazajistán', 'kazajo', 'KZ', 'KAZ'),
('Kirguistán', 'kirguís', 'KG', 'KGZ'),
('Kuwait', 'kuwaití', 'KW', 'KWT'),
('Laos', 'laosiano', 'LA', 'LAO'),
('Líbano', 'libanés', 'LB', 'LBN'),
('Malasia', 'malasio', 'MY', 'MYS'),
('Maldivas', 'maldivo', 'MV', 'MDV'),
('Mongolia', 'mongol', 'MN', 'MNG'),
('Birmania', 'birmano', 'MM', 'MMR'),
('Nepal', 'nepalí', 'NP', 'NPL'),
('Omán', 'omaní', 'OM', 'OMN'),
('Pakistán', 'pakistaní', 'PK', 'PAK'),
('Palestina', 'palestino', 'PS', 'PSE'),
('Singapur', 'singapurense', 'SG', 'SGP'),
('Siria', 'sirio', 'SY', 'SYR'),
('Sri Lanka', 'esrilanqués', 'LK', 'LKA'),
('Tailandia', 'tailandés', 'TH', 'THA'),
('Taiwán', 'taiwanés', 'TW', 'TWN'),
('Tayikistán', 'tayiko', 'TJ', 'TJK'),
('Timor Oriental', 'timorense', 'TL', 'TLS'),
('Turkmenistán', 'turcomano', 'TM', 'TKM'),
('Turquía', 'turco', 'TR', 'TUR'),
('Uzbekistán', 'uzbeko', 'UZ', 'UZB'),
('Vietnam', 'vietnamita', 'VN', 'VNM'),
('Yemen', 'yemení', 'YE', 'YEM'),
('Albania', 'albanés', 'AL', 'ALB'),
('Alemania', 'alemán', 'DE', 'DEU'),
('Andorra', 'andorrano', 'AD', 'AND'),
('Austria', 'austríaco', 'AT', 'AUT'),
('Bélgica', 'belga', 'BE', 'BEL'),
('Bielorrusia', 'bielorruso', 'BY', 'BLR'),
('Bosnia y Herzegovina', 'bosnio', 'BA', 'BIH'),
('Bulgaria', 'búlgaro', 'BG', 'BGR'),
('Ciudad del Vaticano', 'vaticano', 'VA', 'VAT'),
('Croacia', 'croata', 'HR', 'HRV'),
('Dinamarca', 'danés', 'DK', 'DNK'),
('Eslovaquia', 'eslovaco', 'SK', 'SVK'),
('Eslovenia', 'esloveno', 'SI', 'SVN'),
('España', 'español', 'ES', 'ESP'),
('Estonia', 'estonio', 'EE', 'EST'),
('Finlandia', 'finlandés', 'FI', 'FIN'),
('Francia', 'francés', 'FR', 'FRA'),
('Grecia', 'griego', 'GR', 'GRC'),
('Hungría', 'húngaro', 'HU', 'HUN'),
('Irlanda', 'irlandés', 'IE', 'IRL'),
('Islandia', 'islandés', 'IS', 'ISL'),
('Italia', 'italiano', 'IT', 'ITA'),
('Letonia', 'letón', 'LV', 'LVA'),
('Liechtenstein', 'liechtensteiniano', 'LI', 'LIE'),
('Lituania', 'lituano', 'LT', 'LTU'),
('Luxemburgo', 'luxemburgués', 'LU', 'LUX'),
('Macedonia del Norte', 'macedonio', 'MK', 'MKD'),
('Malta', 'maltés', 'MT', 'MLT'),
('Moldavia', 'moldavo', 'MD', 'MDA'),
('Mónaco', 'monegasco', 'MC', 'MCO'),
('Montenegro', 'montenegrino', 'ME', 'MNE'),
('Noruega', 'noruego', 'NO', 'NOR'),
('Países Bajos', 'neerlandés', 'NL', 'NLD'),
('Polonia', 'polaco', 'PL', 'POL'),
('Portugal', 'portugués', 'PT', 'PRT'),
('Reino Unido', 'británico', 'GB', 'GBR'),
('República Checa', 'checo', 'CZ', 'CZE'),
('Rumanía', 'rumano', 'RO', 'ROU'),
('Rusia', 'ruso', 'RU', 'RUS'),
('San Marino', 'sanmarinense', 'SM', 'SMR'),
('Serbia', 'serbio', 'RS', 'SRB'),
('Suecia', 'sueco', 'SE', 'SWE'),
('Suiza', 'suizo', 'CH', 'CHE'),
('Ucrania', 'ucraniano', 'UA', 'UKR'),
('Australia', 'australiano', 'AU', 'AUS'),
('Fiyi', 'fiyiano', 'FJ', 'FJI'),
('Islas Marshall', 'marshalés', 'MH', 'MHL'),
('Islas Salomón', 'salomonense', 'SB', 'SLB'),
('Kiribati', 'kiribatiano', 'KI', 'KIR'),
('Micronesia', 'micronesio', 'FM', 'FSM'),
('Nauru', 'nauruano', 'NR', 'NRU'),
('Nueva Zelanda', 'neozelandés', 'NZ', 'NZL'),
('Palaos', 'palauano', 'PW', 'PLW'),
('Papúa Nueva Guinea', 'papú', 'PG', 'PNG'),
('Samoa', 'samoano', 'WS', 'WSM'),
('Tonga', 'tongano', 'TO', 'TON'),
('Tuvalu', 'tuvaluano', 'TV', 'TUV'),
('Vanuatu', 'vanuatuense', 'VU', 'VUT');